### ISSUE TITLE
Problems with mounting agents

### ISSUE THREAD

**Issue by charon-1-1** [roborescue/adf-sample-agent-java#14]
I want to consult a problem encountered in operation. After I executed the command `bash launch.sh -all `, the interface remained in loading, and the agent did not run successfully

![image](https://user-images.githubusercontent.com/67632791/158390661-9339f7fa-3f8e-4d6b-a213-4f902a78bd58.png)

**Comment by gnardin** [comment]
@charon-1-1 
The console log shows that the agents have been connected. The % does not reach 100%, it will remain in 75% until the end of the simulation.

To run the simulation, you need to select the button `Run` in the `Kernel GUI` window.

**Comment by charon-1-1** [comment]
I successfully ran the sample code following your instructions, but when I tried to switch the map, I found that the RUN button was missing from the Kernel GUI. Figure 1 shows the example code running with the Run button, and Figure 2 shows me trying to switch maps. I wonder if there is something wrong with my command to switch the map(The command I use is `bash start-comprun.sh -m ../maps/kobe/map`).Could you please give me some instructions for switching map?
![Figure1](https://user-images.githubusercontent.com/67632791/158511468-bbffde6c-8d07-4fbb-9e34-bcb77496828a.png)
![Figure2](https://user-images.githubusercontent.com/67632791/158511486-dbeb29f9-e4db-44e1-8f89-44f3f360f3a2.png)

**Comment by gnardin** [comment]
@charon-1-1 
To run the simulation you are using the wrong script. You should use `start.sh` in order to see the `Run` button because the `start-comprun.sh` uses the `--autorun` flag when running the kernel, which means that it launches the simulation after 3 or 5 minutes automatically. The `start-comprun.sh` is a script used to run the competitions in a remote machine.

The proper command to run the simulator with a different scenario, for example `Kobe`, is

```
cd scripts
./start.sh -m ../maps/kobe/map -c ../maps/kobe/config
```
Here I set both the map and the configuration files associated to the `Kobe` scenario. If you do not set the `-m` or the `-c`, then the default map and configurations are used.

**Comment by gnardin** [comment]
There was a change on the Server Port number due to a conflict on MacOS.
The simulator server does not use port 7000 anymore, but port 27931.
This was the only change that should affect the execution of legacy code on the new server. All other changes were internal to the server infrastructure and should not impact the execution of legacy code.

Please let us know if you face any further problem.

**Comment by charon-1-1** [comment]
I tried to modify the port, but the terminal was stuck and could not execute downward any more. Is there something wrong with my command?
![adferror2](https://user-images.githubusercontent.com/67632791/158611788-d5f60e92-8c26-4c76-95a2-a656b7db525f.png)
