### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by charon-1-1** [roborescue/adf-sample-agent-java#17]
Hello, we are trying to convert the old code to the new framework failed to compile. We put the old code in the src folder in the new framework and replaced the **module.cfg** file, but the following error occurred when mounting the agent using the `bash launch.sh -all` command
![image](https://user-images.githubusercontent.com/67632791/162617501-593c023f-4c11-4853-a030-107b6b07f077.png)

**Comment by gnardin** [comment]
Dear @charon-1-1 
No errors are shown in the screenshot shared.
Please provide more detailed log information about the errors generated.

I suggest you to not replace the new `module.cfg` file by your old `module.cfg` file. You should edit the new `module.cfg` file and adjust the required entries to your code. I say that because the default module paths have changed and we updated them in the new `module.cfg` file appropriately.
